// <auto-generated />
namespace Todo.DataAccess.Migrations
{
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Seed2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Seed2));
        
        string IMigrationMetadata.Id
        {
            get { return "201302151024210_Seed2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
